mysql: &mysql
  adapter: mysql2
  encoding: utf8mb4
  host: db
  username: root
  password: 123456
  pool: 5
postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *mysql
  database: project_development
test:
  <<: *mysql
  database: project_test
production:
  <<: *postgres
  database: project_production
  username: project
  password: <%= ENV['PROJECT_PASSWORD'] %>
